# -*- coding: utf-8 -*-
"""introduction-data-science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jA97IRCcervuWcEbEta-ehU95LEsKeQe

## Learning Data Science

`
"""

import pandas as pd
import seaborn as sns
#Read archive csv
note =pd.read_csv("ratings.csv")
##Show dataview x quantity  
note.head(5)

#show lines and columuns
note.shape

#show notes variation
note['rating'].unique()

#show read count notes and number repetition 
note["rating"].value_counts()

#show average all notes
print('media =',notas["rating"].mean())
#show median all notes
print('medina =',notas["rating"].median())

#showing the histogram, passing parameters
note.rating.plot(kind='hist')

#showing others information
note.rating.describe()

#show quartils 
sns.boxplot(note.rating)

"""# Show info other csv"""

#read archive movies and view head csv 
movies = pd.read_csv("movies.csv")
movies.head()

#show notes with movieId =1  , observable in movies, 1= Toy Story
note.query("movieId==1")

"""# Analitycs notes wit one film"""

#average with one film
note.groupby("movieId").mean()["rating"]