# -*- coding: utf-8 -*-
"""introduction-data-science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jA97IRCcervuWcEbEta-ehU95LEsKeQe
"""

import pandas as pd
#Read archive csv
note =pd.read_csv("ratings.csv")
##Show dataview x quantity  
note.head(5)

#show lines and columuns
note.shape

#show notes variation
note['rating'].unique()

#show read count notes and number repetition 
note["rating"].value_counts()

#show median all notes
notas["rating"].mean()